config/routes.rb
Rails.application.routes.draw do
  resources :posts
   root 'posts#index'

end

app/models/post.rb
class Post < ActiveRecord::Base
	validates :image, presence: true
	has_attached_file :image, styles: { :medium => "640x", :thumb => "100x" }
	validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	def index
		@posts = Post.all
	end
	
	def new
		@post = Post.new
	end

	def create
		@post = Post.create(post_params)

		if @post.save
			redirect_to @post
		else
			render :new
		end
	end

	def show
		@post = Post.find(params[:id])
	end

	private 

	def post_params
		params.require(:post).permit(:caption,:image)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.haml
!!! 5
%html  
  %head
    %title Instagem
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true 
    = csrf_meta_tags
  %body
    %nav.navbar.navbar-default
      .navbar-container
        .navbar-header
          %button.navbar-toggle.collapsed{"data-target" => "#bs-navbar-collapse-1", "data-toggle" => "collapse", type: "button"}
            %span.sr-only Toggle Navigation
            %span.icon-bar
            %span.icon-bar
          .navbar-brand= link_to "Photogram", root_path
        .collapse.navbar-collapse#bs-navbar-collapse-1
          %ul.nav.navbar-nav.navbar-right
            %li
              = link_to "New Post", new_post_path
            %li
              = link_to "Login", '#'
            %li
              = link_to "Register", '#'
    = yield

app/views/posts/_show_post.html.haml
.post
  .post-head
    .name
      Tbjoern
  .image.center-block
    = link_to (image_tag @post.image.url(:medium), class:'img-responsive'), post_path(@post)
  %p.caption
    = @post.caption

app/views/posts/index.html.haml
.posts-wrapper.row
  - @posts.each do |post|
    - @post = post
    = render :partial => 'show_post'

app/views/posts/new.html.haml
.form-wrapper.row
  %h1 New Post
  = simple_form_for @post do |f|
    .form-group
      = f.input :caption, input_html: {class: 'form-control'}
    .form-group
      = f.input :image, as: :file
    = f.button :submit, class: 'btn-success'

app/views/posts/show.html.haml
.posts-wrapper.row
  = render 'show_post'